name: CI File Check

on:
  push:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Get source
        uses: actions/checkout@v4

      - name: Check file
        run: |
          if [ -f "test.txt" ]; then
            echo "test.txt exists"
          else
            echo "test.txt does not exist"
            exit 1
          fi